Silverpeas/Silverpeas-Components

suggestion-box/suggestion-box-war/src/main/webapp/suggestionBox/jsp/javaScript/angularjs/directives/suggestionbox-validation.js

Please also take into account PR https://github.com/Silverpeas/Silverpeas-Core/pull/594.

Bug #6257: using the new function isNotDefined() on JavaScript String prototype instead of isWhitespace function that seems to be gone... strange

---

mailinglist/mailinglist-jar/src/test/resources/create-database.sql
mailinglist/mailinglist-war/src/test/resources/create-database.sql

Linked PR: https://github.com/Silverpeas/Silverpeas-Core/pull/597

Feature #6169 : limit the number of recipients of a notification.

---

kmelia/kmelia-ejb/src/main/java/com/silverpeas/kmelia/notification/AbstractKmeliaPublicationUserNotification.java
mailinglist/mailinglist-jar/src/test/resources/org/silverpeas/lookAndFeel/generalLook.properties

Don't forget to take into account PR: https://github.com/Silverpeas/Silverpeas-Core/pull/602

Feature #6170 : handling DEACTIVATED behavior on aimed parts of the application

---

gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/process/GalleryProcessManagement.java
kmelia/kmelia-config/src/main/config/xmlcomponents/kmelia.xml
kmelia/kmelia-ejb/src/main/java/com/silverpeas/kmelia/notification/AbstractKmeliaPublicationUserNotification.java
kmelia/kmelia-ejb/src/main/java/com/stratelia/webactiv/kmelia/control/ejb/KmeliaBmEJB.java
kmelia/kmelia-ejb/src/main/java/com/stratelia/webactiv/kmelia/control/ejb/KmeliaHelper.java
kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/kmax.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/kmax_axisReport.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/kmax_viewCombination.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp
organizationchart/organizationchart-jar/src/main/java/com/silverpeas/components/organizationchart/service/OrganizationChartLdapServiceImpl.java
scheduleevent/scheduleevent-war/src/main/webapp/scheduleevent/jsp/detail.jsp

See tracker.silverpeas.org for further information according to commit description...
Do not omit to get PR on Silverpeas-Core

Several bugs fixes

---

formsonline/formsonline-war/src/main/webapp/formsOnline/jsp/styleSheets/formsOnline.css
quizz/quizz-war/src/main/webapp/quizz/jsp/styleSheets/quizz.css

transfert de propriétés css qui étaient dans global alors que liées à une application en particulier

Lie à la branche du meme nom

---

classifieds/classifieds-war/src/main/webapp/classifieds/jsp/styleSheets/classifieds.css
kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/xmlForm.jsp

Fixing some bugs : 6100, 6618 and 6644

---

kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationPaths.jsp

See commit details and tracker.silverpeas.org for further information...

Bugs fix : 6763 and 6805

---

yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/model/GroupDetail.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/YellowpagesSessionController.java

Doesn't set explicitly the direct number and the total number of users in a group as they are taken in charge by the Group class itself

Fix bug 6937

---

process-manager/process-manager-ejb/src/main/java/com/silverpeas/processManager/ProcessManagerInstanciator.java
process-manager/process-manager-war/src/main/java/com/silverpeas/processManager/servlets/ProcessManagerRequestRouter.java
process-manager/process-manager-war/src/main/webapp/processManager/jsp/viewHistory.jsp
wiki/wiki-war/src/main/java/com/ecyrd/jspwiki/attachment/SilverpeasAttachmentServlet.java

See commit details and tracker.silverpeas.org for further information...
Do not omit PR on Silverpeas-Core.

Several bug fixes on 5.14.x

---

kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java

application administrator can change topic profile even if he had no access right on folder.

fixing bug #7090 Relaxation of security rules 

---

almanach/almanach-config/src/main/config/properties/org/silverpeas/almanach/multilang/almanach.properties
almanach/almanach-config/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_de.properties
almanach/almanach-config/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_en.properties
almanach/almanach-config/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_fr.properties
almanach/almanach-war/src/main/java/com/stratelia/webactiv/almanach/servlets/AlmanachRequestRouter.java
almanach/almanach-war/src/main/webapp/almanach/jsp/createEvent.jsp
almanach/almanach-war/src/main/webapp/almanach/jsp/editEvent.jsp
almanach/almanach-war/src/main/webapp/almanach/jsp/viewEventContent.jsp

Changing checkbox label 'Priority' by 'Important'
Widening of WYSIWYG editor

closing feature #7103. Removing tabs on event view.

---

webpages/webpages-war/src/main/webapp/webPages/jsp/display.jsp

https://tracker.silverpeas.org/issues/7097

Bug #7097: fixing the non display of document previewer/viewer.

---

yellowpages/yellowpages-config/src/main/config/initialize/yellowpagesInitializeSettings.properties
yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/YellowpagesCallBack.java
yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/control/ejb/YellowpagesBm.java
yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/control/ejb/YellowpagesBmEJB.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/DisplayContactsHelper.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/YellowpagesSessionController.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/servlets/YellowpagesRequestRouter.java

Three bugs on 'yellowpages' app

---

yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/control/ejb/YellowpagesBmEJB.java
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/annuaire.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/contact.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/contactManager.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/styleSheets/yellowpages.css
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/topicManager.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/userFull.jsp

See commit details...
Do not forget corresponding PR on Silverpeas-Core.

Feature 6912 on 'yellowpages' app

---

project-manager/project-manager-war/src/main/webapp/projectManager/jsp/projectView.jsp

Replace old method call on SimpleDocument which doesn't exist anymore (getAuthor)

fixing bug #7080 replace old method call on SimpleDocument 

---

almanach/almanach-ejb/src/main/java/com/stratelia/webactiv/almanach/model/EventDetail.java
almanach/almanach-war/src/main/java/com/stratelia/webactiv/almanach/control/AlmanachSessionController.java
almanach/almanach-war/src/main/java/com/stratelia/webactiv/almanach/servlets/AlmanachRequestRouter.java
almanach/almanach-war/src/main/webapp/almanach/jsp/createEvent.jsp
almanach/almanach-war/src/main/webapp/almanach/jsp/editEvent.jsp
almanach/almanach-war/src/main/webapp/almanach/jsp/viewEventContent.jsp

Using "volatile id" service.
In the same time, images were not resized on server-side. This is fixed too.

Bug #7018 on 'almanach' app

---

datawarning/datawarning-jar/src/main/java/com/silverpeas/dataWarning/DataWarningDBDrivers.java

Class loading error when trying to load xml configuration file.

fixing bug #6104 class loading error

---

forums/forums-ejb/src/test/java/com/stratelia/webactiv/forums/forumsManager/ejb/mock/SubscriptionServiceMock.java
suggestion-box/suggestion-box-jar/src/test/java/org/silverpeas/components/suggestionbox/mock/SubscriptionServiceMockWrapper.java

REDMINE https://tracker.silverpeas.org/issues/6909
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/661

Bug #6909 - 5.15.x - fixing some wrong behaviors around the subscription management services (accessible only from kmelia application for now)

---

gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/diaporama.tag
gallery/gallery-war/src/main/webapp/gallery/jsp/styleSheets/slider/themes/classic/galleria.classic.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/oneLevel.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationsToValidate.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/simpleListOfPublications.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp

Using it into the diaporama TAG of gallery application.
Using if into the publication list views of kmelia application.
Using if into the publication validation view of kmelia application.
Linkedt to https://github.com/Silverpeas/Silverpeas-Core/pull/662

New view tags which override script and link HTML tags have been added in order to handle the web browser cache.

---

process-manager/process-manager-war/src/main/java/com/silverpeas/processManager/ProcessManagerSessionController.java

Do not omit to check corresponding PR on Silverpeas-Core...

Fixing bug 7203 on workflows presentationform (empty fields were displayed)

---

suggestion-box/suggestion-box-war/src/main/webapp/suggestionBox/jsp/javaScript/angularjs/directives/suggestionbox-validation.jsp

Regression due to last commit on feature 5661

Fixing bug 7319

---

jdbc-connector/jdbc-connector-war/src/main/webapp/connecteurJDBC/jsp/connecteurJDBC.jsp

Just initialize correctly data array

Fixing bug 7351

---

kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java

Now that fallback is active on form content, content into another language must not be displayed in edition mode...
Do not omit to check out corresponding PR on Silverpeas-Core...

[i18n] Fixing bug 7226

---

gallery/gallery-war/src/main/java/com/silverpeas/gallery/servlets/GalleryRequestRouter.java
gallery/gallery-war/src/main/webapp/gallery/jsp/askMedia.jsp

Closing window after the request is processed...

Fixing bug 7384

---

yellowpages/yellowpages-ejb/src/main/java/com/silverpeas/yellowpages/YellowpagesComponentSettings.java
yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/control/ejb/YellowpagesBmEJB.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/DisplayContactsHelper.java
yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/YellowpagesSessionController.java

- adding Function interface (inspired from functional interfaces of jdk1.8)
- loading by a lazily way the UserFull linked to a ContactDetail
- using new Function interface from ArrayCellText in order to give the possibility to get the text value only when necessary

Bug #1974 - fixing bad performances on massive contact displaying

---

resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/cart.jsp
resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/resource.jsp
resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/resourceManager.jsp
resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/styleSheets/resourcesManager.css

- fixing also missing silverpeas plugins
Linked to https://github.com/Silverpeas/Silverpeas-Core/pull/686

Bug #7191 - fixing the non display of form data of resource (if any) when creating or modifying a resource reservation

---

classifieds/classifieds-war/src/main/webapp/classifieds/jsp/styleSheets/classifieds.css
resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/cart.jsp
resources-manager/resources-manager-war/src/main/webapp/resourcesManager/jsp/styleSheets/resourcesManager.css

Linked to https://github.com/Silverpeas/Silverpeas-Core/pull/687

Bug #7191: adjustments around form display (and the display of form into tips into resource manager application)

---

kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/AjaxPublicationsListServlet.java

Linked to https://github.com/Silverpeas/Silverpeas-Core/pull/691
REDMINE https://tracker.silverpeas.org/issues/7540

Bug #7540: fixing the thumbnail resizing when images come from a gallery component.

---

whitepages/whitepages-jar/src/main/java/com/silverpeas/whitePages/record/UserRecord.java
whitepages/whitepages-war/src/main/java/com/silverpeas/whitePages/control/WhitePagesSessionController.java

Replacing by lazy existing method. Removing useless code.

[Whitepages] Fixing bug 7603

---

almanach/almanach-ejb/src/main/java/com/stratelia/webactiv/almanach/control/CalendarEventEncoder.java
scheduleevent/scheduleevent-jar/src/main/java/com/silverpeas/scheduleevent/service/CalendarEventEncoder.java

Using eventId as part of Uid property (appId-eventId:IP_address).
So, Uid property does not change between each export.
https://tracker.silverpeas.org/issues/7586

[iCal] Fixing bug 7586

---

almanach/almanach-config/src/main/config/xmlcomponents/almanach.xml
blog/blog-config/src/main/config/xmlcomponents/blog.xml
chat/chat-config/src/main/config/xmlcomponents/chat.xml
classifieds/classifieds-config/src/main/config/xmlcomponents/classifieds.xml
formsonline/formsonline-config/src/main/config/xmlcomponents/formsOnline.xml
forums/forums-config/src/main/config/xmlcomponents/forums.xml
gallery/gallery-config/src/main/config/xmlcomponents/gallery.xml
infoletter/infoletter-config/src/main/config/xmlcomponents/infoLetter.xml
jdbc-connector/jdbc-connector-config/src/main/config/xmlcomponents/connecteurJDBC.xml
kmelia/kmelia-config/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_en.properties
kmelia/kmelia-config/src/main/config/xmlcomponents/kmax.xml
kmelia/kmelia-config/src/main/config/xmlcomponents/kmelia.xml
kmelia/kmelia-config/src/main/config/xmlcomponents/toolbox.xml
mailinglist/mailinglist-config/src/main/config/xmlcomponents/mailinglist.xml
mydb/mydb-config/src/main/config/xmlcomponents/myDB.xml
question-reply/question-reply-config/src/main/config/xmlcomponents/questionReply.xml
quickinfo/quickinfo-config/src/main/config/xmlcomponents/quickinfo.xml
quizz/quizz-config/src/main/config/xmlcomponents/quizz.xml
resources-manager/resources-manager-config/src/main/config/xmlcomponents/resourcesManager.xml
rssaggregator/rssaggregator-config/src/main/config/xmlcomponents/rssAgregator.xml
silvercrawler/silvercrawler-config/src/main/config/xmlcomponents/silverCrawler.xml
suggestion-box/suggestion-box-config/src/main/config/xmlcomponents/suggestionBox.xml
survey/survey-config/src/main/config/xmlcomponents/survey.xml
websites/websites-config/src/main/config/xmlcomponents/webSites.xml
whitepages/whitepages-config/src/main/config/xmlcomponents/whitePages.xml
wiki/wiki-config/src/main/config/xmlcomponents/wiki.xml
yellowpages/yellowpages-config/src/main/config/xmlcomponents/yellowpages.xml

Renaming apps 'Administrators' into 'Managers'...
Do not forget to check out PR on Silverpeas-Core.

[UI] Fixing bug 7663

---

gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/dao/MediaDAO.java

Linked to REDMINE https://tracker.silverpeas.org/issues/7665
Please applying this PR only on 5.15.x branch.
Indeed, version 6.x is already fixed.

Bug #7665: fixing a technical problem on gallery components containing more than 500 photos.

---

question-reply/question-reply-war/src/main/webapp/questionReply/jsp/css/question-reply-css.jsp

Ajoute un ciblage de la propriété .action - supprimer l'interférence avec la pop up Responsable de l'application

Fix Bug #7655

---

gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/editMediaLayout.tag
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/viewMediaLayout.tag
gallery/gallery-war/src/main/webapp/gallery/jsp/javaScript/silverpeas-gallery-slider.js
organizationchart/organizationchart-war/src/main/webapp/organizationchart/jsp/chart.jsp
pom.xml
resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/javaScript/resourceManager-calendar.js
resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/portlet.jsp
webPages/webPages-war/src/main/webapp/webPages/jsp/display.jsp

Please check PRs:
* https://github.com/Silverpeas/Silverpeas-Project/pull/1
* https://github.com/Silverpeas/Silverpeas-Core/pull/734

Feature #7909: bye bye frameset

---

almanach/almanach-library/src/main/java/org/silverpeas/components/almanach/model/EventOccurrence.java
infoLetter/infoLetter-library/src/main/java/org/silverpeas/components/infoletter/model/InfoLetter.java
infoLetter/infoLetter-library/src/main/java/org/silverpeas/components/infoletter/model/InfoLetterPublication.java
organizationchart/organizationchart-library/src/main/java/org/silverpeas/components/organizationchart/model/OrganizationalPerson.java
rssAggregator/rssAggregator-library/src/main/java/org/silverpeas/components/rssaggregator/model/RSSItem.java
whitePages/whitePages-library/src/main/java/org/silverpeas/components/whitepages/control/CardHeader.java

Merge also the PR #733 in Silverpeas Core

Fix the bugs detected by sonar

---

gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/control/ejb/GalleryBm.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/control/ejb/GalleryBmEJB.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/dao/MediaDAO.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/dao/MediaSQLQueryBuilder.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/model/AlbumDetail.java
gallery/gallery-ejb/src/test/java/com/silverpeas/gallery/control/ejb/GalleryBmEJBTest.java
gallery/gallery-ejb/src/test/java/com/silverpeas/gallery/dao/MediaDaoTest.java
gallery/gallery-war/src/main/java/com/silverpeas/gallery/control/GallerySessionController.java

REDMINE https://tracker.silverpeas.org/issues/7974

Getting best performances when entering the Gallery application and browsing the albums.

---

blog/blog-jar/src/main/java/com/silverpeas/blog/control/DefaultBlogService.java
blog/blog-jar/src/main/java/com/silverpeas/blog/notification/AbstractBlogUserNotification.java
blog/blog-jar/src/main/java/com/silverpeas/blog/notification/BlogUserAlertNotification.java
blog/blog-jar/src/main/java/com/silverpeas/blog/notification/BlogUserSubscriptionNotification.java
blog/blog-war/src/main/java/com/silverpeas/blog/control/BlogSessionController.java

Fixing notifications management... one for manual notifications, another for subscriptions.

[Blog] Fixing bug 8056

---

kmelia/kmelia-config/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle.properties
kmelia/kmelia-config/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_de.properties
kmelia/kmelia-config/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_en.properties
kmelia/kmelia-config/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_fr.properties
kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java

Adding explicit message when publication is not available to user.

fixing bug 8192. 

---

gallery/gallery-war/src/main/webapp/gallery/jsp/searchAdvanced.jsp
gallery/gallery-war/src/main/webapp/gallery/jsp/styleSheets/gallery.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css
whitePages/whitePages-war/src/main/webapp/whitePages/jsp/dynamicSearch.jsp

Certains boutons utilisaient encore le style milieuBoutonV5 (les boutons de recherche dans l annuaire d experts et dans la recherche de la galerie)

lie a Bug #8281 

---

gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/GalleryComponentSettings.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/MediaHelper.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/constant/MediaMimeType.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/constant/MediaResolution.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/constant/MediaType.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/control/ejb/GalleryBmEJB.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/model/InternalMedia.java
gallery/gallery-ejb/src/main/java/com/silverpeas/gallery/process/GalleryProcessManagement.java
gallery/gallery-ejb/src/test/java/com/silverpeas/gallery/model/PhotoDetailTest.java
gallery/gallery-ejb/src/test/java/com/silverpeas/gallery/model/PhotoTest.java
gallery/gallery-war/src/main/java/com/silverpeas/gallery/servlets/GalleryInWysiwygRouter.java

Using now ImageTool services in order to resize pictures.
Bug #8182 - Handling the thumbnails as same format as original one.
Features #862 & #1237 have been implicitly solved!
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/774

Bug #8303, Bug #8182, Features #862 & #1237- Fixing memory leak problems around massive imports of media into Gallery application.

---

kmelia/kmelia-ejb/src/main/java/com/stratelia/webactiv/kmelia/control/ejb/KmeliaBmEJB.java
suggestion-box/suggestion-box-jar/src/test/java/org/silverpeas/components/suggestionbox/mock/WysiwygManagerMockWrapper.java

Signature of involved method has been changed by deleting an useless parameter.
Do not omit to check out PR on Silverpeas-Core...

[GED] Fixing bug 8291

---

almanach/almanach-war/src/main/webapp/almanach/jsp/styleSheets/almanach.css
gallery/gallery-war/src/main/webapp/gallery/jsp/styleSheets/gallery.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css

On galery, one propertie (position relative) miss, enjoy this change to clean. On kmelia i try perfecting presentation of reader + cleaning.On almanach only cleaning

Adjustment css and cleaning

---

gallery/gallery-war/src/main/webapp/gallery/jsp/javaScript/silverpeas-gallery-slider.js
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/oneLevel.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/simpleListOfPublications.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp

Take into account some changes done in Silverpeas-Core for the chat service.
This has to be merged along the [PR #785](https://github.com/Silverpeas/Silverpeas-Core/pull/785)

Feature 8272

---

delegatednews/delegatednews-war/src/main/webapp/delegatednews/jsp/listNews.jsp
quickinfo/quickinfo-configuration/src/main/config/properties/org/silverpeas/quickinfo/multilang/quickinfo.properties
quickinfo/quickinfo-configuration/src/main/config/properties/org/silverpeas/quickinfo/multilang/quickinfo_de.properties
quickinfo/quickinfo-configuration/src/main/config/properties/org/silverpeas/quickinfo/multilang/quickinfo_en.properties
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/News.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/repository/NewsRepository.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/control/QuickInfoSessionController.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/servlets/QuickInfoRequestRouter.java

Integration of the PR [512](https://github.com/Silverpeas/Silverpeas-Components/pull/512) into Silverpeas 6

fixing bug #8423 by optimizing code

---

kmelia/kmelia-war/src/main/java/com/silverpeas/portlets/LastPublicationsPortlet.java
kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/KmeliaTransversal.java

Do not forget PR on Silverpeas-Core...

[Portlets] Fixing bug 8459

---

kmelia/kmelia-ejb/src/main/java/com/silverpeas/kmelia/workflowextensions/SendInKmelia.java

[Workflow -> GED] Fixing bugs 8460 and 8540

---

forums/forums-library/src/main/java/org/silverpeas/components/forums/service/DefaultForumService.java
forums/forums-library/src/main/java/org/silverpeas/components/forums/service/ForumsDAO.java
projectManager/projectManager-library/src/main/java/org/silverpeas/components/projectmanager/model/ProjectManagerCalendarDAO.java
projectManager/projectManager-library/src/main/java/org/silverpeas/components/projectmanager/model/ProjectManagerDAO.java
projectManager/projectManager-library/src/main/java/org/silverpeas/components/projectmanager/service/DefaultProjectManagerService.java

- fixing mistakes made around JDBC queries
- fixing an ArrayOfBoundException around a special case of forum deletion
- fixing some SonarQube feedbacks

Bug #8513: fixing effective deletions of instances of forum or project manager which were in error

---

almanach/almanach-war/src/test-awaiting/resources/org/silverpeas/peasCore/URLManager.properties
forums/forums-war/src/test-awaiting/resources/com/stratelia/silverpeas/peasCore/URLManager.properties
mailinglist/mailinglist-war/src/test-awaiting/resources/org/silverpeas/peasCore/URLManager.properties
whitePages/whitePages-war/src/main/webapp/WEB-INF/web.xml

Don't forget to merge also the PR https://github.com/Silverpeas/Silverpeas-Core/pull/810

Replace the invocation of the old chat client by the one of SilverChat

---

suggestionBox/suggestionBox-library/src/main/java/org/silverpeas/components/suggestionbox/repository/SuggestionRepository.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/817

Feature #8789: introducing SilverpeasList and adding some parameters about the pagination display.

---

hyperlink/hyperlink-configuration/src/main/config/properties/org/silverpeas/hyperlink/multilang/hyperlinkBundle.properties
hyperlink/hyperlink-configuration/src/main/config/properties/org/silverpeas/hyperlink/multilang/hyperlinkBundle_fr.properties
hyperlink/hyperlink-war/src/main/java/org/silverpeas/components/hyperlink/control/HyperlinkSessionController.java
hyperlink/hyperlink-war/src/main/java/org/silverpeas/components/hyperlink/servlets/HyperlinkRequestRouter.java
hyperlink/hyperlink-war/src/main/webapp/hyperlink/jsp/check.jsp
hyperlink/hyperlink-war/src/main/webapp/hyperlink/jsp/redirect.jsp
hyperlink/hyperlink-war/src/main/webapp/hyperlink/jsp/sso.jsp

#1681, #1682 and #6300
Do not forget PR on Silverpeas-Core...

[Hyperlink / SSO] Closing some features

---

kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_de.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_en.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_fr.properties
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/KmeliaPublication.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css

indicates original publication from a shortcut

[GED] closing feature 6573

---

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/checkKmelia.jsp
processManager/processManager-configuration/src/main/config/data/workflowRepository/DemandeCongesSimple/DemandeCongesSimple.xml
processManager/processManager-war/src/main/java/org/silverpeas/processmanager/ProcessManagerSessionController.java
processManager/processManager-war/src/main/java/org/silverpeas/processmanager/servlets/ProcessManagerRequestRouter.java
processManager/processManager-war/src/main/webapp/processManager/jsp/attachmentManager.jsp
processManager/processManager-war/src/main/webapp/processManager/jsp/editAction.jsp
processManager/processManager-war/src/main/webapp/processManager/jsp/listProcess.jsp
processManager/processManager-war/src/main/webapp/processManager/jsp/listTasks.jsp
projectManager/projectManager-war/src/main/webapp/projectManager/jsp/check.jsp
questionReply/questionReply-war/src/main/java/org/silverpeas/components/questionreply/control/QuestionReplyExport.java

Take PR https://github.com/Silverpeas/Silverpeas-Components/pull/551 and rebase it from master
Using JAXB and JPA instead of Castor.
This concerns Silverpeas import/export and workflow functionnalities.
Do not forget to process PR on Silverpeas-Core, Silverpeas-dependencies-bom and Silverpeas-Distribution

workflow without castor

---

formsOnline/formsOnline-library/src/integration-test/java/org/silverpeas/components/formsonline/model/FormsOnlineDAOJdbcTest.java
formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/DefaultFormsOnlineService.java
formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineDAO.java
formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineDAOJdbc.java
formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineService.java
formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/RequestsByStatus.java
formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/control/FormsOnlineSessionController.java
formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/control/RequestItem.java
formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/servlets/FormsOnlineRequestRouter.java
formsOnline/formsOnline-war/src/main/webapp/formsOnline/jsp/editForm.jsp
formsOnline/formsOnline-war/src/main/webapp/formsOnline/jsp/formsList.jsp
formsOnline/formsOnline-war/src/main/webapp/formsOnline/jsp/inbox.jsp

- handling pagination page on service and persistence side
- using new DataItemWrapper
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/843

Using common tool in order get optimized displaying of list handled by the FormsOnline application

---

silverCrawler/silverCrawler-library/pom.xml
silverCrawler/silverCrawler-library/src/main/java/org/silverpeas/components/silvercrawler/model/FileFolder.java

Don't forget to merge the following PRs before this one and in that order:
https://github.com/Silverpeas/Silverpeas-Jackrabbit-JCA/pull/2
https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/5
https://github.com/Silverpeas/Silverpeas-Core/pull/847
And then the following PR after this one:
https://github.com/SilverTeamWork/Silverpeas-Distribution/pull/2

Update the version of lucene to the one provided by Wildfly 10.1.0

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/export/ODTDocumentBuilder.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/ui/ResultSearchRenderer.java
resourcesManager/resourcesManager-war/src/main/java/org/silverpeas/components/resourcesmanager/web/ReservationEntity.java

Don't forget to merge before PR https://github.com/Silverpeas/Silverpeas-Core/pull/868

closing feature #9495

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaDocumentSubscriptionPublicationUserNotification.java

Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/873

Bug #9601: avoiding a technical error when notifying manually on versionned attachment of a publication which is a copy of another one.

---

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css

Please enter the commit message for your changes. Lines starting

Fix bug #9617 qui est un bug produit

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/webapp/WEB-INF/tags/silverpeas/kmelia/paste.tag
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp

From 6.0.x, there were critical errors reported by sonar.
But it was a little bit misunderstandable...
So, trying the same modifications on master branch in order to check if sonar does the same report.

Report of bug #9263 #9238 and #9596.

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java

Fixing bug about i18n and WYSIWYG field

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/workflowextensions/SendInKmelia.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java

Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/883

Bug 8676 9268 report

---

yellowpages/yellowpages-war/src/main/java/org/silverpeas/components/yellowpages/control/YellowpagesSessionController.java
yellowpages/yellowpages-war/src/main/java/org/silverpeas/components/yellowpages/servlets/YellowpagesRequestRouter.java
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/annuaire.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/styleSheets/yellowpages.css

Do not forget PR on Silverpeas-Core...

[Yellow pages] fixing bugs 9615 and 9630

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java

Changes made to preventing a NullPointerException during one-screen creation of publication (form based) in KmeliaSessionController.java are already done in master...

[ECM] Fixing bug #9813

---

almanach/almanach-war/src/main/webapp/almanach/jsp/almanachPortlet.jsp
blog/blog-war/src/main/webapp/blog/jsp/accueil.jsp
blog/blog-war/src/main/webapp/blog/jsp/viewPost.jsp
forums/forums-war/src/main/webapp/forums/jsp/javaScript/viewMessage.js
jdbcConnector/jdbcConnector-war/src/main/webapp/connecteurJDBC/jsp/portlet.jsp
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/topicReport.jsp
questionReply/questionReply-war/src/main/webapp/questionReply/jsp/listQuestionsDHTML.jsp
questionReply/questionReply-war/src/main/webapp/questionReply/jsp/portlet.jsp
quickinfo/quickinfo-war/src/main/webapp/portlets/jsp/quickInfos/portlet.jsp
quizz/quizz-war/src/main/webapp/quizz/jsp/quizzAdmin.jsp
quizz/quizz-war/src/main/webapp/quizz/jsp/quizzUser.jsp
resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/javaScript/resourceManager-calendar.js
resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/portlet.jsp
scheduleEvent/scheduleEvent-war/src/main/webapp/scheduleevent/jsp/list.jsp
silverCrawler/silverCrawler-war/src/main/webapp/silverCrawler/jsp/portlet.jsp
silverCrawler/silverCrawler-war/src/main/webapp/silverCrawler/jsp/viewDirectory.jsp
survey/survey-war/src/main/webapp/survey/jsp/surveyList.jsp
survey/survey-war/src/main/webapp/survey/jsp/surveyUtils.jsp

- wiring sp.element.scrollTo & setScrollTo into Forum component
- wiring Kmelia publication lister & topic & portlet
- wiring Blog list & post
- wiring FAQ pages
- wiring Quizz
- wiring ScheduleEvent
- wiring SilverCrawler
- wiring Survey
- wiring QuickInfo
- wiring resourceManager portlet
- wiring JdbcConnector portlet
- wiring almanach portlet
Linked to PRs:
- https://github.com/Silverpeas/Silverpeas-Core/pull/901
- https://github.com/Silverpeas/Silverpeas-Looks/pull/28

UI navigation improvements

---

gallery/gallery-configuration/src/main/config/xmlcomponents/gallery.xml
gallery/gallery-library/src/integration-test/java/org/silverpeas/components/gallery/model/SoundIT.java
gallery/gallery-library/src/integration-test/java/org/silverpeas/components/gallery/model/StreamingIT.java
gallery/gallery-library/src/integration-test/java/org/silverpeas/components/gallery/model/VideoIT.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/GalleryComponentSettings.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/MediaUtil.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/Watermark.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/constant/MediaResolution.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/model/InternalMedia.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/model/Streaming.java
gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/web/AbstractGalleryResource.java
gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/web/PhotoEntity.java
gallery/gallery-war/src/main/webapp/gallery/jsp/javaScript/silverpeas-gallery-slider.js

A new resolution "NORMAL" is now computed. It is a copy of the original picture, but well oriented according to EXIF meta data.
Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/917

Feature #3371 & #9944: orientation of picture and image watermarking.

---

classifieds/classifieds-library/src/main/java/org/silverpeas/components/classifieds/service/DefaultClassifiedService.java
classifieds/classifieds-war/src/main/java/org/silverpeas/components/classifieds/control/ClassifiedsSessionController.java
forums/forums-library/src/integration-test/java/org/silverpeas/components/forums/ForumsInstancePreDestructionIT.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/AbstractKmeliaSimulationElementLister.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaPublicationSimulationElementLister.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/export/ODTDocumentBuilder.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp
projectManager/projectManager-library/src/main/java/org/silverpeas/components/projectmanager/service/DefaultProjectManagerService.java
questionReply/questionReply-war/src/main/java/org/silverpeas/components/questionreply/control/QuestionReplyExport.java
questionReply/questionReply-war/src/main/java/org/silverpeas/components/questionreply/web/ReplyResource.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/News.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/control/SurveySessionController.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/923

Feature #5778: viewing attachment contents linked to a kmelia contribution.

---

almanach/almanach-war/src/main/webapp/almanach/jsp/almanachOccurrenceView.jsp
forums/forums-war/src/main/webapp/forums/jsp/viewMessage.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/clone.jsp
projectManager/projectManager-war/src/main/webapp/projectManager/jsp/taskView.jsp
questionReply/questionReply-war/src/main/webapp/questionReply/jsp/listQuestionsDHTML.jsp
resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/viewReservation.jsp
suggestionBox/suggestionBox-war/src/main/webapp/suggestionBox/jsp/suggestionView.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/929

Feature #5778: wiring components almanach, userCalenda, questionReply, suggestionBox, forums, projectManager and resourcesManager.

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/KmeliaTransversal.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java

For now, the latest publications feature gets benefits of this work.
Using the pagination mechanism which permits to combines pagination on a data source with functional pagination.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/944

Trying to optimize the loading of publications.

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/KmeliaTransversal.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/readingControlManager.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/946

Making optimizations in order to increase performances about the last visitor feature.

---

dataWarning/dataWarning-war/src/main/webapp/dataWarning/jsp/connectionParameters.jsp
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/constant/StreamingProvider.java
gallery/gallery-war/src/main/webapp/gallery/jsp/welcome.jsp
gallery/gallery-war/src/main/webapp/gallery/jsp/wysiwygBrowser.jsp
hyperlink/hyperlink-war/src/main/java/org/silverpeas/components/hyperlink/servlets/HyperlinkRequestRouter.java
hyperlink/hyperlink-war/src/main/webapp/hyperlink/jsp/internal.jsp
hyperlink/hyperlink-war/src/main/webapp/hyperlink/jsp/redirect.jsp
jdbcConnector/jdbcConnector-war/src/main/webapp/connecteurJDBC/jsp/connectionParameters.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp
mydb/mydb-war/src/main/webapp/myDB/jsp/connectionSettings.jsp
survey/survey-war/src/main/java/org/silverpeas/components/survey/servlets/RecordParticipation.java

A set of commits to fix some vulnerabilities.
Don't forget to merge before:
- https://github.com/Silverpeas/Silverpeas-Core/pull/969
And after:
- https://github.com/Silverpeas/Silverpeas-Looks/pull/34
To test you have to use the more recent silverpeas 6.1 distribution.

Bug security

---

delegatednews/delegatednews-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
formsOnline/formsOnline-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
forums/forums-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
gallery/gallery-library/pom.xml
gallery/gallery-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
infoLetter/infoLetter-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
kmelia/kmelia-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaAttachmentEventListener.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaOperationContext.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java
mailinglist/mailinglist-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
pom.xml
quickinfo/quickinfo-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/News.java
resourcesManager/resourcesManager-library/src/integration-test/resources/META-INF/test-MANIFEST.MF
whitePages/whitePages-library/src/integration-test/resources/META-INF/test-MANIFEST.MF

Please, integrate before:
- https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/8
- https://github.com/Silverpeas/Silverpeas-Core/pull/977
And then:
- https://github.com/Silverpeas/Silverpeas-Assembly/pull/17

Update the version of SCIM library dependency

---

processManager/processManager-war/src/main/webapp/processManager/jsp/styleSheets/processManager.css
suggestionBox/suggestionBox-war/src/main/java/org/silverpeas/components/suggestionbox/web/SuggestionBoxResource.java

Linked to PR:
* https://github.com/Silverpeas/Silverpeas-Core/pull/986
* https://github.com/Silverpeas/Silverpeas-Looks/pull/35

Feature #10729: inbox user notification improvements

---

Jenkinsfile

Linked to PR:
- https://github.com/Silverpeas/Silverpeas-Core/pull/990
- https://github.com/Silverpeas/Silverpeas-Looks/pull/38

Feature #26: Trying to manage a lock file in order to handle build dependencies.

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/importexport/KmeliaImportExport.java

Fixing also some sonar feedback.

Bug #10906: fixing error about Kmelia Drag&Drop of folders.

---

delegatednews/delegatednews-library/src/main/java/org/silverpeas/components/delegatednews/DelegatedPublicationEventListener.java
delegatednews/delegatednews-library/src/main/java/org/silverpeas/components/delegatednews/service/DelegatedNewsService.java
delegatednews/delegatednews-library/src/main/java/org/silverpeas/components/delegatednews/service/DelegatedNewsServiceImpl.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaDelayedVisibilityUserNotificationReminder.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaDelayedVisibilityUserNotificationReminderInitializer.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaInstanceContributionManager.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/QuickInfoComponentSettings.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/News.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/NewsModel.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/QuickInfoInstanceContributionManager.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/QuickInfoService.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/notification/NewsEvent.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/notification/NewsEventNotifier.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/notification/QuickInfoDelayedVisibilityUserNotificationReminder.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/notification/QuickInfoDelayedVisibilityUserNotificationReminderInitializer.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/control/QuickInfoSessionController.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1006

Bug #10671: making the sending of user subscriptions possible with publication or news having a visibility period set in the future.

---

Jenkinsfile
mydb/mydb-library/src/main/java/org/silverpeas/components/mydb/model/JdbcRequester.java

In MyDB, when fetching the list of tables in the data source, check for each of
them they can be accessed by the current connected user.

Bug #10905

---

gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/servlets/GalleryRequestRouter.java
gallery/gallery-war/src/main/webapp/gallery/jsp/searchAdvanced.jsp

Fixing also easy sonar feedback.

Bug #11088: pagination is now working with search results.

---

webPages/webPages-configuration/src/main/config/xmlcomponents/webPages.xml
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/control/WebPagesSessionController.java
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/servlets/WebPagesRequestRouter.java
webPages/webPages-war/src/main/webapp/webPages/jsp/check.jsp
webPages/webPages-war/src/main/webapp/webPages/jsp/display.jsp

- adding manager role to webPages component without data recovery
- the subscription management menu is now provided only for webPages managers
- cleaning some useless code
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1039

Bug #10897: fixing some stuffs discovered around WebPages component

---

quickinfo/quickinfo-configuration/src/main/config/properties/org/silverpeas/quickinfo/settings/quickInfoSettings.properties
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/servlets/QuickInfoRequestRouter.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/web/AbstractNewsResource.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/web/NewsEntity.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/web/NewsResource.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/web/TickerResource.java
quickinfo/quickinfo-war/src/main/webapp/WEB-INF/tags/silverpeas/quickinfo/portletNews.tag
quickinfo/quickinfo-war/src/main/webapp/portlets/jsp/quickInfos/portlet.jsp
quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/home.jsp
quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/styleSheets/quickinfo.css

Using the new accumulative list pane for mosaic view.

[quickinfo-optims] Trying to make improve performances around quickinfo component.

---

survey/survey-war/src/main/java/org/silverpeas/components/survey/control/SurveySessionController.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/servlets/SurveyRequestRouter.java
survey/survey-war/src/main/webapp/survey/jsp/surveyDetail.jsp
survey/survey-war/src/main/webapp/survey/jsp/surveyList.jsp
survey/survey-war/src/main/webapp/survey/jsp/surveyUtils.jsp

Do not forget https://github.com/Silverpeas/Silverpeas-Core/pull/1095

Bug #11585 : optimizing display of results

---

delegatednews/delegatednews-library/src/integration-test/resources/arquillian.xml
formsOnline/formsOnline-library/src/integration-test/resources/arquillian.xml
forums/forums-library/src/integration-test/resources/arquillian.xml
gallery/gallery-library/src/integration-test/resources/arquillian.xml
infoLetter/infoLetter-library/src/integration-test/resources/arquillian.xml
kmelia/kmelia-library/src/integration-test/resources/arquillian.xml
mailinglist/mailinglist-library/src/integration-test/resources/arquillian.xml
quickinfo/quickinfo-library/src/integration-test/resources/arquillian.xml
resourcesManager/resourcesManager-library/src/integration-test/resources/arquillian.xml
whitePages/whitePages-library/src/integration-test/resources/arquillian.xml

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1129

Trying other arquillian configuration.

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java

Now, all the copies and moves are righly managed into kmelia against the transversal rules, like the one of space storage quota.
IF OK, THIS PR WILL BE INTEGRATED IMMEDIATELY BY MYSELF
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1145

Feature #12035: using the refactoring of simulation process in order to be used from anywhere, with several source contexts.

---

webPages/webPages-configuration/src/main/config/xmlcomponents/webPages.xml
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/control/WebPagesSessionController.java
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/servlets/WebPagesRequestRouter.java
webPages/webPages-war/src/main/webapp/webPages/jsp/display.jsp
webPages/webPages-war/src/main/webapp/webPages/jsp/editXMLContent.jsp

Do not forget to check out https://github.com/Silverpeas/Silverpeas-Core/pull/1152 and https://github.com/Silverpeas/Silverpeas-Looks/pull/53

Feature #12442 : two templates for a single 'webPages' app

---

Jenkinsfile
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaAttachmentEventListener.java

Remove declarations of unraised exceptions in KmeliaAttachmentEventListener
Don't forget to merge before PR https://github.com/Silverpeas/Silverpeas-Core/pull/1150

Bug #12443

---

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/attachmentLinkManagement.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1157

Bug #12503: making filebank ckeditor plugin working again.

---

forums/forums-library/src/main/java/org/silverpeas/components/forums/subscription/ForumsSubscriptionService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaSubscriptionPublicationUserNotification.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1161

Bug #12581: fixing the subscription validation popin which was not displayed in some cases when it was supposed to

---

blog/blog-war/src/main/java/org/silverpeas/components/blog/control/BlogSessionController.java
blog/blog-war/src/main/webapp/blog/jsp/colonneDroite.jsp

Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Core/pull/1160
* https://github.com/Silverpeas/Silverpeas-Looks/pull/55

Feature #12037-9605: refactoring bookmarks by adding category management

---

classifieds/classifieds-war/src/main/java/org/silverpeas/components/classifieds/control/ClassifiedsSessionController.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/KmeliaPublication.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/CmisKmeliaContributionsProvider.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaPublicationBatchSimulationElementLister.java
processManager/processManager-library/src/main/java/org/silverpeas/processmanager/service/DefaultProcessManagerService.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/control/SurveySessionController.java

Don't forget to merge also https://github.com/Silverpeas/Silverpeas-Core/pull/1172

Feature 11841

---

almanach/almanach-war/pom.xml
kmelia/kmelia-library/pom.xml
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/workflowextensions/SendInKmelia.java
kmelia/kmelia-war/pom.xml
pom.xml

Updating old library itext to the most recent one.
Updating Log4j to 2.15 version.
Linked to PRs:
* https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/25
* https://github.com/Silverpeas/silverpeas-test-dependencies-bom/pull/7
* https://github.com/Silverpeas/Silverpeas-Project/pull/7
* https://github.com/Silverpeas/Silverpeas-Core/pull/1178
* https://github.com/Silverpeas/Silverpeas-Looks/pull/56
* https://github.com/Silverpeas/Silverpeas-Assembly/pull/20
* https://github.com/Silverpeas/silverpeasmobile/pull/26

Bug #12648

---

almanach/almanach-war/pom.xml
kmelia/kmelia-library/pom.xml
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/workflowextensions/SendInKmelia.java
kmelia/kmelia-war/pom.xml
pom.xml

Updating old library itext to the most recent one.
Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Core/pull/1179
* https://github.com/Silverpeas/Silverpeas-Looks/pull/57
* https://github.com/Silverpeas/silverpeasmobile/pull/27
* https://github.com/Silverpeas/Silverpeas-Assembly/pull/21

Bug #12648 / 6.3.x

---

mailinglist/mailinglist-library/src/integration-test/resources/org/silverpeas/components/mailinglist/service/model/create-database.sql
mailinglist/mailinglist-library/src/integration-test/resources/org/silverpeas/components/mailinglist/service/model/dao/create-database.sql
yellowpages/yellowpages-library/src/main/java/org/silverpeas/components/yellowpages/service/DefaultYellowpagesService.java
yellowpages/yellowpages-library/src/main/java/org/silverpeas/components/yellowpages/service/YellowpagesService.java
yellowpages/yellowpages-war/src/main/java/org/silverpeas/components/yellowpages/control/YellowpagesSessionController.java

Taking into account the group states into yellow pages application.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1207

Feature #11914: applying st_group structure changes.

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaContributionIndicatorInitializer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java

Adding into kmelia a NewContributionIndicator implementation.
Adding the 'new-contribution' HTML element class to list of publications displayed into context of kmelia component.
Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Core/pull/1213
* https://github.com/Silverpeas/Silverpeas-Looks/pull/61

Feature #12039: display indicator of new contribution

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/AbstractPublicationComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliAuthorComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliCreationDateComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliDescriptionComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliImportanceComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliRankComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliTitleComparator.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/model/PubliUpdateDateComparator.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/SearchContext.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/Sort.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/searchInTopic.js

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1214

Bug #13000: fixing kmelia local search behavior

---

forums/forums-war/src/main/java/org/silverpeas/components/forums/servlets/ForumsRequestRouter.java
forums/forums-war/src/main/webapp/forums/jsp/viewMessage.jsp

Fix bug.
Replace displayAttachedFiles.jsp import by the view tag displayAttachments in viewMessage.jsp
Don't forget to merge before https://github.com/Silverpeas/Silverpeas-Core/pull/1229

Bug #13173

---

forums/forums-war/src/main/webapp/forums/jsp/javaScript/viewMessage.js
forums/forums-war/src/main/webapp/forums/jsp/viewMessage.jsp
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/jstl/KmeliaDisplayHelper.java
quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/styleSheets/quickinfo.css
survey/survey-war/src/main/webapp/survey/jsp/styleSheets/survey.css

Fixing some strange behaviors in forums UI.
Making the scolling to right message listening to new DOM events.
Implementing a new scrolling to item mechanism dedicated to forum behavior.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1230

Bug #5089: making displayAttachedFiles.jsp callable several times into a same HTML page.

---

classifieds/classifieds-war/src/main/webapp/classifieds/jsp/accueil.jsp
classifieds/classifieds-war/src/main/webapp/classifieds/jsp/classifiedManager.jsp
formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/servlets/FormsOnlineRequestRouter.java
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/editMedia.tag
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/editMediaLayout.tag
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/xmlForm.jsp
webPages/webPages-war/src/main/webapp/webPages/jsp/editXMLContent.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/contactManager.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1244

Bug #13261: Improvement of the default value of a form field

---

classifieds/classifieds-war/src/main/webapp/classifieds/jsp/accueil.jsp
classifieds/classifieds-war/src/main/webapp/classifieds/jsp/classifiedManager.jsp
formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/servlets/FormsOnlineRequestRouter.java
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/editMedia.tag
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/editMediaLayout.tag
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/xmlForm.jsp
webPages/webPages-war/src/main/webapp/webPages/jsp/editXMLContent.jsp
yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/contactManager.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1245

Bug 13261-6.4.x: Improvement of the default value of a form field

---

community/community-war/src/main/webapp/community/jsp/javaScript/vuejs/components/silverpeas-community.js
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_de.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_en.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_fr.properties
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/JSONServlet.java
kmelia/kmelia-war/src/main/webapp/WEB-INF/tags/silverpeas/kmelia/dragAndDrop.tag
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/vuejs/components/kmelia-contribution-templates.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/vuejs/components/kmelia-contribution.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/vuejs/components/kmelia-contribution.js
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement-templates.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1241

Feature #7270: Wiring with the new JavaScript plugin signatures.

---

community/community-war/src/main/java/org/silverpeas/components/community/control/CommunityWebController.java
community/community-war/src/main/webapp/community/jsp/javaScript/vuejs/components/silverpeas-community-membership.js
community/community-war/src/main/webapp/community/jsp/javaScript/vuejs/components/silverpeas-community.js
community/community-war/src/main/webapp/community/jsp/main.jsp
kmelia/kmelia-war/src/main/webapp/WEB-INF/tags/silverpeas/kmelia/dragAndDrop.tag
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/vuejs/components/kmelia-contribution.js
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement-templates.jsp
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement.js
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement.service.js
processManager/processManager-war/src/main/webapp/processManager/jsp/replacements.jsp

Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Core/pull/1250
* https://github.com/Silverpeas/Silverpeas-Looks/pull/68

Migrating to VueJs 3.x

---

processManager/processManager-war/src/main/webapp/processManager/jsp/viewProcess.jsp

bug #13390: Support of presentationForm.js in presentation Form

---

processManager/processManager-war/src/main/java/org/silverpeas/processmanager/ProcessManagerSessionController.java
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement-templates.jsp
processManager/processManager-war/src/main/webapp/processManager/jsp/javaScript/vuejs/replacement.service.js

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1259

Feature 13497: it is now possible in a workflow to continue to replace an incumbent in a REMOVED state by a substitute.

---

spaceMembers/spaceMembers-configuration/src/main/config/xmlcomponents/spaceMembers.xml
spaceMembers/spaceMembers-war/src/main/java/org/silverpeas/components/spacemembers/control/SpaceMembersSessionController.java
spaceMembers/spaceMembers-war/src/main/java/org/silverpeas/components/spacemembers/servlets/SpaceMembersRequestRouter.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1267

Feature #13552: adding new component parameter to Members of Space component.

---

community/community-library/src/main/java/org/silverpeas/components/community/security/authorization/CommunityInstanceSimpleDocumentAccessControlExtension.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1271

Bug #13546: fixing to anonymous user an unauthorized access when displaying images from presentation page of a community

---

forums/forums-war/src/main/java/org/silverpeas/components/forums/control/ForumsSessionController.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/service/ScheduledAlertUser.java
gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/control/GallerySessionController.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1273

Bug #13549: fixing administration cache management problem

---

blog/blog-configuration/src/main/config/xmlcomponents/blog.xml
blog/blog-library/src/main/java/org/silverpeas/components/blog/service/BlogService.java
blog/blog-library/src/main/java/org/silverpeas/components/blog/service/DefaultBlogService.java
blog/blog-war/src/main/java/org/silverpeas/components/blog/control/BlogSessionController.java
blog/blog-war/src/main/java/org/silverpeas/components/blog/servlets/BlogRequestRouter.java
blog/blog-war/src/main/webapp/blog/jsp/postManager.jsp
kmelia/kmelia-configuration/src/main/config/xmlcomponents/kmelia.xml
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp
quickinfo/quickinfo-configuration/src/main/config/xmlcomponents/quickinfo.xml
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java
quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/control/QuickInfoSessionController.java
quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/quickInfoEdit.jsp

On kmelia, quickinfos and blog.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1288

Bug #13591: fixing PDC classification management from contribution header update.

---

processManager/processManager-configuration/src/main/config/properties/org/silverpeas/processManager/multilang/processManagerBundle.properties
processManager/processManager-configuration/src/main/config/properties/org/silverpeas/processManager/multilang/processManagerBundle_de.properties
processManager/processManager-configuration/src/main/config/properties/org/silverpeas/processManager/multilang/processManagerBundle_en.properties
processManager/processManager-configuration/src/main/config/properties/org/silverpeas/processManager/multilang/processManagerBundle_fr.properties
processManager/processManager-library/src/main/java/org/silverpeas/processmanager/ProcessFilter.java
processManager/processManager-war/src/main/java/org/silverpeas/processmanager/ProcessManagerSessionController.java
processManager/processManager-war/src/main/java/org/silverpeas/processmanager/servlets/ProcessManagerRequestRouter.java
processManager/processManager-war/src/main/webapp/processManager/jsp/listProcess.jsp

Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1289

Feature #13619 : Display improvements on the instances List

---

almanach/almanach-war/src/main/java/org/silverpeas/components/almanach/ResultSearchRenderer.java
classifieds/classifieds-library/src/main/java/org/silverpeas/components/classifieds/service/DefaultClassifiedService.java
forums/forums-library/src/main/java/org/silverpeas/components/forums/service/DefaultForumService.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/model/MediaSelection.java
gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/process/media/GalleryIndexMediaDataProcess.java
infoLetter/infoLetter-library/src/main/java/org/silverpeas/components/infoletter/InfoLetterInstancePostConstruction.java
infoLetter/infoLetter-library/src/main/java/org/silverpeas/components/infoletter/implementation/InfoLetterDataManager.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/ui/ResultSearchRenderer.java
mailinglist/mailinglist-library/src/main/java/org/silverpeas/components/mailinglist/service/model/MessageIndexer.java
projectManager/projectManager-library/src/main/java/org/silverpeas/components/projectmanager/service/DefaultProjectManagerService.java
questionReply/questionReply-library/src/main/java/org/silverpeas/components/questionreply/index/QuestionIndexer.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/NewsSelection.java
resourcesManager/resourcesManager-library/src/main/java/org/silverpeas/components/resourcesmanager/service/SimpleResourcesManager.java
suggestionBox/suggestionBox-library/src/main/java/org/silverpeas/components/suggestionbox/repository/SuggestionRepository.java
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/WebPagesIndexer.java
webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/control/WebPagesSessionController.java
whitePages/whitePages-library/src/main/java/org/silverpeas/components/whitepages/control/CardManager.java

Take into the change in the way to build an IndexEntry object.
Don't forget to merge before PR https://github.com/Silverpeas/Silverpeas-Core/pull/1306

Feature #13448

---

survey/survey-configuration/src/main/config/properties/org/silverpeas/survey/multilang/surveyBundle.properties
survey/survey-configuration/src/main/config/properties/org/silverpeas/survey/multilang/surveyBundle_de.properties
survey/survey-configuration/src/main/config/properties/org/silverpeas/survey/multilang/surveyBundle_en.properties
survey/survey-configuration/src/main/config/properties/org/silverpeas/survey/multilang/surveyBundle_fr.properties
survey/survey-war/pom.xml
survey/survey-war/src/main/java/org/silverpeas/components/survey/control/DisplayResultView.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/control/SurveySessionController.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/servlets/SurveyRequestRouter.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/web/AnswerEntity.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/web/AnswerPercentEntity.java
survey/survey-war/src/main/java/org/silverpeas/components/survey/web/html/SurveyJavascriptPluginInclusion.java
survey/survey-war/src/main/webapp/survey/jsp/js/vuejs/components/silverpeas-survey-result-chart-templates.jsp
survey/survey-war/src/main/webapp/survey/jsp/js/vuejs/components/silverpeas-survey-result-chart.css
survey/survey-war/src/main/webapp/survey/jsp/js/vuejs/components/silverpeas-survey-result-chart.js
survey/survey-war/src/main/webapp/survey/jsp/styleSheets/survey.css
survey/survey-war/src/main/webapp/survey/jsp/surveyDetail.jsp
survey/survey-war/src/main/webapp/survey/jsp/surveyUtils.jsp
survey/survey-war/src/test/java/org/silverpeas/components/survey/web/WebEntityTest.java
survey/survey-war/src/test/resources/META-INF/services/org.silverpeas.core.util.BeanContainer

* defining result views
* keeping the chosen result view into session
* starting to create some WEB entities which might be used when moving to WEB service architecture
* implementing new VueJS components in order to render the result pages
* adding print action with helping messages about print and export actions
Linked PRs:
* https://github.com/Silverpeas/Silverpeas-Core/pull/1307
* https://github.com/Silverpeas/Silverpeas-Looks/pull/77

Feature #13830 and #13831: improving survey result pages.

---

kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_de.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_en.properties
kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_fr.properties
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationPaths.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview4PublicationPaths.jsp

New VueJS component allowing to browse spaces and components has been wired into management page of publication locations into kmelia component.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1328

Feature #13992: allowing to restrict a document template to a set of spaces

---

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java

DefaultKmeliaService asks for indexation of a new publication after this one was put into a given topic only if it is indexable.
Related to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1343

Bug #13512

---

whitePages/whitePages-war/src/main/java/org/silverpeas/components/whitepages/filters/LoginFilter.java

Takes into account the redirection parameters are now defined into the new class WebRedirection in Silverpeas Core.
Requires https://github.com/Silverpeas/Silverpeas-Core/pull/1356 to be merged

Bug #14387 Takes into account the redirection parameters are now defined

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java

Fix the issue by specifying the XML form for local search can be only the one set at for the whole Kmelia instance.

Bug #14417

---

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/ForbiddenAccessRenderer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/LastPublicationsRenderer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/NothingRenderer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/PublicationFragmentSettings.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/PublicationsRenderer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/Renderer.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/RenderingContext.java
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/checkKmelia.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/defermentMotive.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/importMultiFiles.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/importOneFile.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/kmax_axisReport.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/orderPublications.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationsList.jsp
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css
kmelia/kmelia-war/src/main/webapp/kmelia/jsp/topicReport.jsp

In several peculiar locations, the filename, title or description of an attachment aren't correctly escaped for HTML rendering. Fix those issues.
Refactor the rendering process in AjaxPublicationListServlet in order first to separate in a way some responsibilities, and to fix the issues sent back by Sonar.
This PR is related to the following PR: https://github.com/Silverpeas/Silverpeas-Core/pull/1360
And the following PR belongs to this one as to the above one: https://github.com/Silverpeas/Silverpeas-Looks/pull/89

Bug #14478

---

community/community-library/src/integration-test/java/org/silverpeas/components/community/CommunityManagementIT.java
community/community-library/src/main/java/org/silverpeas/components/community/model/CommunityOfUsers.java
community/community-library/src/test/java/org/silverpeas/components/community/CommunityOfUsersTest.java

Take into account of the renaming of SpaceInst#getSpaceProfileInst to SpaceInst#getDirectSpaceProfileInst
Related to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1372

Bug #13273

---

gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/model/MediaSelection.java
gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/control/GallerySessionController.java
kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/NewsSelection.java
yellowpages/yellowpages-library/src/main/java/org/silverpeas/components/yellowpages/model/YellowPagesGroupDetail.java
yellowpages/yellowpages-war/src/main/java/org/silverpeas/components/yellowpages/control/YellowpagesSessionController.java

Take into account change in Silverpeas-Core.

Feature #3990

---

gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/constant/GalleryResourceURIs.java
gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/servlets/GalleryRequestRouter.java
gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/viewMediaLayout.tag
gallery/gallery-war/src/main/webapp/gallery/jsp/mediaPhotoView.jsp

Take into account the download of files is now the only and default behavior in Silverpeas when serving files.
Related to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1394

Bug #14784
