Silverpeas/Silverpeas-Components

yellowpages/yellowpages-ejb/src/main/java/com/stratelia/webactiv/yellowpages/model/GroupDetail.java, yellowpages/yellowpages-war/src/main/java/com/stratelia/webactiv/yellowpages/control/YellowpagesSessionController.java
Doesn't set explicitly the direct number and the total number of users in a group as they are taken in charge by the Group class itself
The fix comes from cherry-picking the commits in 5.14.x
=> Fix bug 6937 for 5.15

kmelia/kmelia-war/src/main/java/com/stratelia/webactiv/kmelia/servlets/KmeliaRequestRouter.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp, quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/news.jsp
Using the new tag that handles the call of displayAttachedFiles.jsp (instead of calling it directly...) into publication display.
Fixing also a problem into quick info application, by using the new tag.
The problem occurred when adding an attachment just after the creation of a news: it was duplicating the news !
Linked to https://github.com/Silverpeas/Silverpeas-Core/pull/655
=> Feature #6071: skipping notification sending from attachment actions performed from publication page of kmelia application.

almanach/almanach-war/src/main/webapp/almanach/jsp/calendar.jsp, almanach/almanach-war/src/main/webapp/almanach/jsp/listOfEvents.jsp, almanach/almanach-war/src/main/webapp/almanach/jsp/portletCalendar.jsp, classifieds/classifieds-war/src/main/webapp/classifieds/jsp/accueil.jsp, classifieds/classifieds-war/src/main/webapp/classifieds/jsp/accueilNotCategorized.jsp, classifieds/classifieds-war/src/main/webapp/classifieds/jsp/classifiedsResult.jsp, gallery/gallery-war/src/main/webapp/gallery/jsp/javaScript/silverpeas-gallery-slider.js, kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle.properties, kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/multilang/kmeliaBundle_fr.properties, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/web/FolderResource.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/glossaryHighlight.js, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp, resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/almanach.jsp, resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/javaScript/resourceManager-calendar.js, resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/portlet.jsp, resourcesManager/resourcesManager-war/src/main/webapp/resourcesManager/jsp/styleSheets/resourcesManager.css, rssAggregator/rssAggregator-war/src/main/webapp/rssAgregator/jsp/displayRSS.jsp, rssAggregator/rssAggregator-war/src/main/webapp/rssAgregator/jsp/rssPortletView.jsp, yellowpages/yellowpages-war/src/main/webapp/yellowpages/jsp/topicManager.jsp
The following Javascript libraries/plugins are updated (with their CSS):
* JQuery,
* JQuery-UI,
* QTip,
* Noty,
* RateIt,
* JSTree,
* FullCalendar,
* CKEditor,
* AngularJS.
Warning: jquery-migrate-1.4.1.min.js isn't really minified. It is distributed under this name in order to avoid the build system to minify it. Keep it non-minified lets us to have warnings from it on detected deprecated uses of JQuery. But, this lib should be remove before the release of Silverpeas 6.0 (it would be nice to remove it for the release of 6.0-alpha2)
Don't forget to merge also the PR [#748](https://github.com/Silverpeas/Silverpeas-Core/pull/749) in Silverpeas-Core.
=> Feature 8046

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp
Report de la modification de la fonction déjà faite en v6 qui corrige la non prise en compte de la taille du descriptif wysiwyg d'un dossier
=> Fix Bug #8804

blog/blog-war/src/main/java/org/silverpeas/components/blog/control/BlogSessionController.java, blog/blog-war/src/main/webapp/blog/jsp/viewPost.jsp, classifieds/classifieds-war/src/main/java/org/silverpeas/components/classifieds/control/ClassifiedsSessionController.java, gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/control/GallerySessionController.java, gallery/gallery-war/src/main/webapp/WEB-INF/tags/silverpeas/gallery/viewMediaLayout.tag, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp, quickinfo/quickinfo-war/src/main/java/org/silverpeas/components/quickinfo/control/QuickInfoSessionController.java, quickinfo/quickinfo-war/src/main/webapp/quickinfo/jsp/news.jsp, suggestionBox/suggestionBox-war/src/main/java/org/silverpeas/components/suggestionbox/control/SuggestionBoxWebController.java, suggestionBox/suggestionBox-war/src/main/webapp/suggestionBox/jsp/suggestionView.jsp, survey/survey-war/src/main/java/org/silverpeas/components/survey/control/SurveySessionController.java, survey/survey-war/src/main/webapp/survey/jsp/surveyDetail.jsp, webPages/webPages-war/src/main/java/org/silverpeas/components/webpages/control/WebPagesSessionController.java
Now the user manual notification has the following improvements:
- the notification window text area is replaced by a WYSIWYG editor to write a more rich text for notification message.
- for manual notifications on a contribution that have attachments, a link to each of the documents attached to the contribution in Silverpeas is automatically added in the notification message when such notifications are sent through SMTP. This concerns both the immediate and the delayed transmission.
Don't forget to merge before the PR https://github.com/Silverpeas/Silverpeas-Core/pull/955
=> Feature 10255

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java
When a user is declared in no profile and component is public, an error appears and folders are not displayed.
=> [Kmelia] fixing bug #10440

almanach/almanach-library/src/main/java/org/silverpeas/components/almanach/workflowextensions/SendInAlmanach.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/workflowextensions/SendInKmelia.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/importexport/KmeliaImportExport.java
In SendInKmelia: the creation of the node(s) into which the publication will
be put are now performed into a new transaction so that if the creation fails
it doesn't rollback all the process and once the creation is done, the nodes
are accessed out of the transaction further in the task execution.
Don't forget to merge before https://github.com/Silverpeas/Silverpeas-Core/pull/962
=> FIx bug #10358

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/styleSheets/kmelia.css
La hauteur 100 % comportait des erreurs - Cela corrige les impactes négatifs sur les pop in (qui étaient coupées si trop haute)
=> Fix le comportement de la hauteur du panel treeview 

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaInstanceManualUserNotification.java
Kmelia use now the facility of receiver filtering by resource in the user
notification module to indicate to the module that the users and the groups to
select must be those that can access a given topic having specific rights
enabled on it or on one of its parent topic.
Don't forget to merge before PR https://github.com/Silverpeas/Silverpeas-Core/pull/1001
=> Bug #10857

mydb/mydb-library/src/main/java/org/silverpeas/components/mydb/model/DbColumn.java, mydb/mydb-library/src/main/java/org/silverpeas/components/mydb/model/JdbcRequester.java, mydb/mydb-war/src/main/webapp/myDB/jsp/mydb.jsp, mydb/mydb-war/src/main/webapp/myDB/jsp/rowForm.jsp
Fix bug #11109. In MyDB, several foreign keys on the same table can be now set
when updating or inserting a new row.
Fix another discovered bug: simple default value of fields in MyDB weren't
taken into account.
Add a new feature: computed default value of fields are now taken in charge:
MyDB asks for the database to compute it. As some default value computation
depends on the context on which they are invoked, the default value is now
figuring out on the demand.
=> Bug #11109

gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/control/GalleryExporter.java, gallery/gallery-war/src/main/java/org/silverpeas/components/gallery/control/GallerySessionController.java
Furthermore, all media (expect streaming ones) are exported (not only images)
=> Bug #11281 : Sub albums are exported without error

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaHelper.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java
Fix the bug by computing the sorting rule each time it is required to sort the
list of publications.
Based upon the PR https://github.com/Silverpeas/Silverpeas-Core/pull/1083
=> Bug #11527

almanach/almanach-configuration/src/main/config/properties/org/silverpeas/almanach/multilang/almanach.properties, almanach/almanach-configuration/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_de.properties, almanach/almanach-configuration/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_en.properties, almanach/almanach-configuration/src/main/config/properties/org/silverpeas/almanach/multilang/almanach_fr.properties, almanach/almanach-configuration/src/main/config/properties/org/silverpeas/almanach/settings/almanachIcons.properties, almanach/almanach-war/src/main/java/org/silverpeas/components/almanach/services/AlmanachWebManager.java, almanach/almanach-war/src/main/webapp/almanach/jsp/almanach.jsp
- adding the new creation actions into the main menu
- adding the possibility to import event from an ICal file
- removing export menu action which was targeting the main calendar only
- cleaning some code
Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/1081
Checking the integration with https://easybacklog.com/accounts/4659/backlogs/355925
=> Feature #10260: creating standard and synchronized calendars from an Almanach instance (without using aggregation).

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/KmeliaTransversal.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/export/ODTDocumentBuilder.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationViewOnly.jsp
Refactoring/renaming services in order to get a right behavior about accessing a publication from the best location.
Fixing a technical problem on alias save which was inducing sometimes aliases loss.
Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/1120
=> Feature #9047: indicating that last publications can be also retrieved from aliases.

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/KmeliaResourcePasting.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/copyApplicationDialog.jsp
Now, when a Kmelia instance is duplicated, both its default
classification (for the instance itself as well as for each of
the nodes) and its PdC utilization are also duplicated.
Update copyApplicationDialog.jsp to set the property of copying the
classification onto the PdC of the publications. So, all specific
classification positions of each publication will be duplicated. This
property is always set at true but it is taken into account only when
the publications are duplicated, that is to say if the property of
copying the publication headers is set at true.
Don't forget to merge before PR https://github.com/Silverpeas/Silverpeas-Core/pull/1153
=> Bug #12479

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/notification/KmeliaSubscriptionPublicationUserNotification.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/updatePublicationsContent.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/xmlForm.jsp
Fixing the fact that a user can modify a contribution for which he has no right!
Fixing the selected checkboxes which was hidden on publication list.
Fixing into KmeliaSessionController the visibility filter performing which was executed before the list of publication was loaded.
Fixing the modification of always visible publicaton into draft status which was not well handled. The valid publication was updated instead of the clone ones.
Linked to PR: https://github.com/Silverpeas/Silverpeas-Core/pull/1155
=> Feature #12035: wiring the modification popins on massive publication update.

formsOnline/formsOnline-configuration/src/main/config/xmlcomponents/formsOnline.xml, formsOnline/formsOnline-library/src/integration-test/java/org/silverpeas/components/formsonline/model/AbstractFormsOnlineIT.java, formsOnline/formsOnline-library/src/integration-test/java/org/silverpeas/components/formsonline/model/FormsOnlineDAOJdbcIT.java, formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/FormsOnlineComponentAuthorization.java, formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/DefaultFormsOnlineService.java, formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineDAO.java, formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineDAOJdbc.java, formsOnline/formsOnline-library/src/main/java/org/silverpeas/components/formsonline/model/FormsOnlineService.java, formsOnline/formsOnline-war/src/main/java/org/silverpeas/components/formsonline/control/FormsOnlineSessionController.java
A new component instance parameter appears: displaySort
3 values : name asc, creationDate asc, creationDate desc
Default value is name asc
=> Bug #13551: The order in which the form is displayed in the list changes after modification

kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/settings/kmeliaSettings.properties, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/jstl/KmeliaDisplayHelper.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/AjaxPublicationsListServlet.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/attachmentLinkManagement.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationLinksManager.jsp
- Publications are displayed by alphabetical order (by default)
- The order can be change by the user with the selectbox
=> Feature #13573 : See also: improve display order of the publications

blog/blog-library/src/main/java/org/silverpeas/components/blog/dao/PostDAO.java, blog/blog-library/src/main/java/org/silverpeas/components/blog/service/BlogFilters.java, blog/blog-library/src/main/java/org/silverpeas/components/blog/service/BlogService.java, blog/blog-library/src/main/java/org/silverpeas/components/blog/service/DefaultBlogService.java, blog/blog-war/src/main/java/org/silverpeas/components/blog/control/BlogSessionController.java, blog/blog-war/src/main/java/org/silverpeas/components/blog/servlets/BlogRequestRouter.java, blog/blog-war/src/main/java/org/silverpeas/components/blog/servlets/BlogRssServlet.java, blog/blog-war/src/main/webapp/blog/jsp/accueil.jsp, blog/blog-war/src/main/webapp/blog/jsp/portlet.jsp
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1319
=> Feature #13789: improving performances into blog loading data.

community/community-library/src/main/java/org/silverpeas/components/community/security/authorization/CommunityInstanceSimpleDocumentAccessControlExtension.java
Applying API modifications without changing any logic.
Linked to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1332
=> Bug #12281: checking simple document access control properly for attendees of event of personal user calendar

community/community-library/src/integration-test/java/org/silverpeas/components/community/CommunityManagementIT.java, community/community-library/src/integration-test/java/org/silverpeas/components/community/CommunityNotificationIT.java, community/community-library/src/integration-test/java/org/silverpeas/components/community/TestScope.java, community/community-library/src/main/java/org/silverpeas/components/community/CommunityInstancePostConstruction.java, community/community-library/src/main/java/org/silverpeas/components/community/CommunityInstancePreDestruction.java, community/community-library/src/main/java/org/silverpeas/components/community/model/CommunityOfUsers.java
Now the creation and the deletion of a community of users is notified. This can be used for external components to access the newly created commiunity of users in order to perform some post-processing with the community.
New CommunityOfUsers#getGroupOfMembers() method. This method returns the group of members in the community. If such a group doesn't yet exist, then it is created for the community of users. It is a way to get all the actual members of a community without having to filter the memberships by their status.
New CommunityOfUsers#getAll() static method to get all the existing community of users.
=> Feature #14033

kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/KmeliaComponentAuthorization.java
A publication is a pueculiar contribution in Silverpeas as iti can be located in several locations in the same or in different component instances. In this case, we have the original publication along with its all aliases. This capability is used in the Kmelia application. As consequence, the publication is only referred uniquely by its local identifier (its local identifier is its global one), whereas the others types of contributions are identified uniquely by their global identifier that is made up of their local identifier and of the identifier of the application instance they belong to.
Despite this peculiarity, the authorization mechanism in Kmelia takes the publication by their local identifier and, in a such context, any access right validation can be incorrect on publication …
=> Bug #14471

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/javaScript/navigation.js
By testing the fix of the bug, I discovered a nasty hidden bug in js when adding a new translation for a given topic: when the properties of a topic is rendered, an HTML select element is updated with the translations of the node's properties. If we ask to see the properties of a topic for which its name and description were translated for all of the supported languages, the HTML select element is correctly updated. But, if after we ask to see the properties of another topic for which a translation is missed, then the HTML select element isn't correctly updated for the missed translation: instead of having for the missing translation an identifier of -1, it kept the id of the translation of the previous selected topic for the same language.
Fix this bug.
Related to the PR …
=> Bug #14503

classifieds/classifieds-library/src/main/java/org/silverpeas/components/classifieds/model/ClassifiedDetail.java, classifieds/classifieds-library/src/main/java/org/silverpeas/components/classifieds/service/DefaultClassifiedService.java
Now, when a classified ad isn't validated, it is not indexable. If a validated classified ad is put in draft (for modification), then its index is deleted. Index is created only for validated classfied ads.
=> Bug #14523

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/renderers/PublicationsRenderer.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/treeview.jsp
Fix the bug. The d&d handling was based upon the .jstree-draggable class. But since the refactoring within the fix of the bug 14478, the <span> with this CSS class didn't receive anymore the mouse event but its <a> parent because this one had a class attribute set. Without the class attribute in the <a> parent, the <span> element succeed to receive any mouse click down event on it. Nevertheless, in order the d&d mechanism works on publications, it was needed to move the id attribute from the <a> element to the <span class=".jstree-draggable> element because this publication identifier is fetched from this id on the dragged HTML node. So, the click event handler of the <a> node required to be refined to take into account of this (because the id attribute was also fetched to figure out the …
=> Bug #14661

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/control/KmeliaSessionController.java, kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java
In Kmelia: when updating a folder within which the local rights are enabled, the admin specific rights of the folder are then initialized with the admin rights inherited from the parent folder. This behavior is then coherent with the creation of a new folder with specific rights.
=> Bug #14391

kmelia/kmelia-war/src/main/java/org/silverpeas/components/kmelia/servlets/KmeliaRequestRouter.java, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/orderPublications.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publication.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationManager.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationViewOnly.jsp, kmelia/kmelia-war/src/main/webapp/kmelia/jsp/publicationsList.jsp
In Kmelia, take into account the publication description can be made up of several sentences. When rendering in HTML, the special characters (like line feed, tabulations, ...) are replaced by their HTML equivalent.
=> Bug #14678

blog/blog-library/src/main/java/org/silverpeas/components/blog/service/DefaultBlogService.java, community/community-library/src/integration-test/resources/community-database.sql, forums/forums-library/src/main/java/org/silverpeas/components/forums/service/DefaultForumService.java, gallery/gallery-library/src/integration-test/resources/org/silverpeas/components/gallery/dao/create-media-database.sql, gallery/gallery-library/src/main/java/org/silverpeas/components/gallery/process/GalleryProcessManagement.java, kmelia/kmelia-configuration/src/main/config/properties/org/silverpeas/kmelia/settings/kmeliaSettings.properties, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/KmeliaPasteDetail.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/DefaultKmeliaService.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaBinsScheduledPurger.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaDeleter.java, kmelia/kmelia-library/src/main/java/org/silverpeas/components/kmelia/service/KmeliaService.java, questionReply/questionReply-war/src/main/java/org/silverpeas/components/questionreply/control/QuestionReplySessionController.java, quickinfo/quickinfo-library/src/main/java/org/silverpeas/components/quickinfo/model/DefaultQuickInfoService.java, webSites/webSites-library/src/main/java/org/silverpeas/components/websites/service/DefaultWebSiteService.java, yellowpages/yellowpages-library/src/main/java/org/silverpeas/components/yellowpages/service/DefaultYellowpagesService.java
Implement a scheduled bins purger for the Kmelia instances. This purger is disabled by default. To enable it, just set the following properties `kmelia.autoDeletionDelay` and `kmelia.autoDeletionCron` in the configuration file `kmeliaSettings.properties`. The first property is to specify the threshold in days a contribution can be kept in a bin before its definitive deletion, and the second property is a CRON statement to plan the execution of the purger.
For its working, the purger uses the new `NodeDetail` and `PublicationDetail` removal attributes to compute the number of days the topics and the publications are in the bins in order to know if they have exceeded the delay.
This PR requires the following one https://github.com/Silverpeas/Silverpeas-Core/pull/1403
=> Feature 10786

kmelia/kmelia-war/src/main/webapp/kmelia/jsp/xmlForm.jsp
When checking a notification about a contribution change has to be triggered, the case of a new form is now taken into account (it was previously discarded).
Related to PR https://github.com/Silverpeas/Silverpeas-Core/pull/1404
=> Bug #14770
